[features]
seeds = true
skip-lint = false

[programs.localnet]
transaction_example = "ancA4duevpt3eSgS5J7cD8oJntmfLKJDM59GhMtegES"

[workspace]
members = [
    "./programs/transaction-example"
]

[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.18"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 5000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 