name: Call Remote Test

on:
  workflow_dispatch:
    inputs:
      program:
        description: "Program to test"
        required: true
        type: string

jobs:
  test:
    uses: Woody4618/github-action/.github/workflows/reusable-test.yaml@main
    with:
      program: ${{ github.event.inputs.program }}
