name: Devnet Build and Deploy with IDL

env:
  SOLANA_VERIFY_VERSION: "0.4.1" # Version of solana-verify to use

on:
  workflow_dispatch:

jobs:
  build:
    uses: Woody4618/github-action/.github/workflows/reusable-build.yaml@v0.1.0
    with:
      program: "transaction_example"
      network: "devnet"
      deploy: true
      upload_idl: true
      verify: false
      use-squads: false
    secrets:
      DEVNET_SOLANA_DEPLOY_URL: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
      DEVNET_DEPLOYER_KEYPAIR: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR }}
