name: Release to mainnet with IDL and verify and use squads

env:
  SOLANA_VERIFY_VERSION: "0.4.1" # Version of solana-verify to use

on:
  workflow_dispatch:

jobs:
  build:
    uses: Woody4618/github-action/.github/workflows/reusable-build.yaml@main
    with:
      program: "transaction_example"
      network: "mainnet"
      deploy: true
      upload_idl: true
      verify: true
      use-squads: true
      priority-fee: 300000
    secrets:
      DEVNET_SOLANA_DEPLOY_URL: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      DEVNET_DEPLOYER_KEYPAIR: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR }}
      DEVNET_MULTISIG: ${{ secrets.DEVNET_MULTISIG }}
      DEVNET_MULTISIG_VAULT: ${{ secrets.DEVNET_MULTISIG_VAULT }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}
