name: Build Program

# Constants
env:
  SOLANA_VERIFY_VERSION: "0.4.0" # Version of solana-verify to use

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      program:
        description: "Program to build"
        required: true
        default: "my_program"
      network:
        description: "Target network for deployment"
        required: false
        default: "devnet"
        type: choice
        options:
          - devnet
          - mainnet
      deploy:
        description: "Deploy program"
        required: false
        type: boolean
        default: false
      upload_idl:
        description: "Upload IDL"
        required: false
        type: boolean
        default: true
      verify:
        description: "Verify build"
        required: false
        type: boolean
        default: true
      use-squads:
        description: "Use Squads for deployment"
        required: false
        type: boolean
        default: false
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

# Required secrets for this workflow:
#   - DEVNET_SOLANA_DEPLOY_URL: The RPC URL for devnet deployments
#   - MAINNET_SOLANA_DEPLOY_URL: The RPC URL for mainnet deployments
#   - DEVNET_DEPLOYER_KEYPAIR: The base58 encoded keypair for devnet deployments
#   - MAINNET_DEPLOYER_KEYPAIR: The base58 encoded keypair for mainnet deployments
#   - PROGRAM_ADDRESS_KEYPAIR: The keypair for initial program deployment (if program doesn't exist)

jobs:
  build:
    uses: Woody4618/github-action/.github/workflows/reusable-build.yaml@main
    with:
      program: ${{ github.event.inputs.program }}
      network: ${{ github.event.inputs.network }}
      deploy: ${{ github.event.inputs.deploy }}
      upload_idl: ${{ github.event.inputs.upload_idl }}
      verify: ${{ github.event.inputs.verify }}
      use-squads: ${{ github.event.inputs.use-squads }}
    secrets:
      DEVNET_SOLANA_DEPLOY_URL: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
      MAINNET_SOLANA_DEPLOY_URL: ${{ secrets.MAINNET_SOLANA_DEPLOY_URL }}
      DEVNET_DEPLOYER_KEYPAIR: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
      MAINNET_DEPLOYER_KEYPAIR: ${{ secrets.MAINNET_DEPLOYER_KEYPAIR }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR }}
      DEVNET_MULTISIG: ${{ secrets.DEVNET_MULTISIG }}
      DEVNET_MULTISIG_VAULT: ${{ secrets.DEVNET_MULTISIG_VAULT }}
      MAINNET_MULTISIG: ${{ secrets.MAINNET_MULTISIG }}
      MAINNET_MULTISIG_VAULT: ${{ secrets.MAINNET_MULTISIG_VAULT }}
