name: Test Program

on:
  workflow_call:
    inputs:
      program:
        description: "Program to test"
        required: true
        type: string
      branch:
        description: "Branch to test"
        required: false
        type: string
        default: "*"

  workflow_dispatch:
    inputs:
      program:
        description: "Program to test"
        required: true
        default: "transaction_example"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: solana-developers/github-actions/extract-versions@0.2.5
        id: versions

      - uses: solana-developers/github-actions/setup-all@0.2.5
        with:
          solana_version: ${{ steps.versions.outputs.solana_version }}
          anchor_version: ${{ steps.versions.outputs.anchor_version }}
          node_version: 18

      - uses: solana-developers/github-actions/run-tests@0.2.5
        with:
          solana_version: ${{ steps.versions.outputs.solana_version }}
          anchor_version: ${{ steps.versions.outputs.anchor_version }}
          program: ${{ inputs.program }}
