name: Build action instead of workflow

env:
  SOLANA_VERIFY_VERSION: "0.4.1" # Version of solana-verify to use

on:
  workflow_dispatch:
    inputs:
      priority_fee:
        description: "Priority fee for transactions"
        required: true
        default: "300000"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Woody4618/solana-github-action-workflow/build@main
        with:
          program: "transaction_example"
          network: "devnet"
          deploy: true
          upload_idl: true
          verify: false
          use-squads: false
          priority-fee: ${{ github.event.inputs.priority_fee }}
